name: vit
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - grpcio=1.71.0
  - intel-openmp=2023.1.0
  - ld_impl_linux-64=2.40
  - libabseil=20250127.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - markdown=3.8
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.5
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openssl=3.0.17
  - packaging=25.0
  - pip=25.2
  - protobuf=5.29.3
  - pthread-stubs=0.3
  - python=3.12.11
  - re2=2024.07.02
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - tbb=2021.8.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - tk=8.6.15
  - tzdata=2025b
  - werkzeug=3.1.3
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - asttokens==3.0.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - executing==2.2.1
      - filelock==3.13.1
      - fonttools==4.59.2
      - fsspec==2024.6.1
      - ipdb==0.13.13
      - ipython==9.5.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - networkx==3.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==11.0.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - stack-data==0.6.3
      - sympy==1.13.3
      - tabulate==0.9.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.4.0
      - typing-extensions==4.12.2
      - wcwidth==0.2.13
      - xlrd==2.0.2
      - xlutils==2.0.0
      - xlwt==1.3.0
