name: embedding
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - asttokens==3.0.1
      - decorator==5.2.1
      - executing==2.2.1
      - filelock==3.20.0
      - fsspec==2025.12.0
      - ipdb==0.13.13
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - markupsafe==2.1.5
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - networkx==3.6.1
      - numpy==2.3.5
      - opencv-python==4.13.0.92
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - stack-data==0.6.3
      - sympy==1.14.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.6.0
      - typing-extensions==4.15.0
      - wcwidth==0.6.0
      - xlrd==2.0.2
      - xlutils==2.0.0
      - xlwt==1.3.0